[package]
name = "typical90"
version = "0.1.0"
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = { version = "0.4.3", features = ["derive"] }
num = "0.4.0"
itertools = "0.10.1"
regex = "1.5.4"

[profile.release]
lto = true
panic = 'abort'
